# SwissTM build
# TMBUILD ?= wlpdstm

# ======== Defines ========
CC       := gcc
#CPPFLAGS += -DNDEBUG
CPPFLAGS += -I../lib -I../common/$(TMBUILD)
CFLAGS   += -Wall -Wextra
CFLAGS   += -O3

LD       := gcc
LDFLAGS  += -lpthread

TMLIBDIR ?= ../../../wlpdstm/
CPPFLAGS += -I$(TMLIBDIR)/include
LDFLAGS  += -L$(TMLIBDIR)/lib -lwlpdstm
LIBDEPS  += $(TMLIBDIR)/lib/libwlpdstm.a

include ../common/Makefile.common
