# tsx-rtm build
#TMBUILD ?= tsx-rtm

# ======== Defines ========
#CC       := gcc
CPPFLAGS += -DNDEBUG
CPPFLAGS += -I../lib -I../common/$(TMBUILD) -DPOWERTM
CFLAGS   += -Wall -Wextra
CFLAGS   += -O3 -mhtm

LD       := $(CC)
LDFLAGS  += -lpthread

TMLIBDIR ?= ../../../htm
CPPFLAGS += -I$(TMLIBDIR)
LDFLAGS  += -L$(TMLIBDIR) -lhtm
LIBDEPS  += $(TMLIBDIR)/libhtm.a

include ../common/Makefile.common
