#TMBUILD ?= norec

# ======== Defines ========
CC       := $(CXX)
CPPFLAGS += -DNDEBUG
CPPFLAGS += -I../lib -I../common/$(TMBUILD) -DSTM -DSTM_API_STAMP
CFLAGS   += -Wall -Wextra
CFLAGS   += -O3

LD       := $(CXX)
LDFLAGS  += -lpthread

TMLIBDIR ?= ../../../NOrec
CPPFLAGS += -I$(TMLIBDIR)/include 
LDFLAGS  += -L$(TMLIBDIR) -lnorec -lrt
#LIBDEPS  += $(TMLIBDIR)/libnorec.a

include ../common/Makefile.common
