
ARCH = $(shell uname -m)

ifeq ($(ARCH), x86_64)
  MSR = ../../../msr

  CPPFLAGS += -I$(MSR)
  LDFLAGS  += -L$(MSR) -lmsr

endif

ifdef PROFILING
  CPPFLAGS += -D$(PROFILING)
endif

LDFLAGS += -lm -lrt 

CPPFLAGS += -D_GNU_SOURCE
